### ISSUE TITLE
Uncaught ReferenceError: django is not defined

### ISSUE THREAD

**Issue by Megido6** [iambrandontaylor/django-admin-sortable#106]
error in adminsortable.js in last line 
...})(django.jQuery);

how to fix it? i use now django 1.4.5

**Comment by alsoicode** [comment]
If you're using a version of Django that old, you need to use django-admin-sortable v1.4.9 or below. The latest version is not compatible with Django 1.4.x

**Comment by Megido6** [comment]
right i use old version of sortable, but static not different

**Comment by alsoicode** [comment]
I'll have to fire up a virtualenv with 1.4.5 and see what's up.

**Comment by alsoicode** [comment]
Is this still an issue? If not I'd like to close this.
