### ISSUE TITLE
Split non-db field parts of Sortable out into a mixin

### ISSUE THREAD

**Issue by andybak** [iambrandontaylor/django-admin-sortable#107]
Unless I've missed something I can't see much else in Sortable that would require it to be anything other than a mix-in. Ideally even the name of the ordering field could be configurable (via a 'get_sort_field' method?)

A mix-in would be less intrusive to add to existing models - especially those that already have their own ordering field.

**Comment by jrief** [comment]
That's one of the reasons I rewrote it, see here https://github.com/jrief/django-admin-sortable2

**Comment by andybak** [comment]
Great. I've got a question or two but I'll post an issue on your repo.

**Comment by alsoicode** [comment]
The `Sortable` model is already an abstract class, and I could make the ordering field configurable... what else would need to change for it to be considered a "mixin" ?

**Comment by andybak** [comment]
That's probably all. Maybe have two classes though - SortableMixin without a db field and maybe BaseSortable that inherits the mixin and adds the field for people that don't already have one

**Comment by alsoicode** [comment]
I can see that. I guess I could leave the `Sortable` class as is for backwards compatibility, and have a new `SortableMixin` that doesn't have the built-in field.

**Comment by alsoicode** [comment]
Actually found some time to work on this, finally. So far things are going well.

**Comment by alsoicode** [comment]
@andybak The new unobtrusive branch: https://github.com/iambrandontaylor/django-admin-sortable/tree/unobtrusive

I haven't run this through Travis yet, but I don't anticipate any issues. Now Sortable doesn't automatically define any model fields or ordering. You can name the ordering field anything you want, as long as it derives from one of Django ORM's integer types. You just have to tell the SortableMixin what field name you want to use for ordering, and set the `ordering` Meta option.

**Comment by alsoicode** [comment]
2.0.0 has been released on PyPi.
