### ISSUE TITLE
Bug in get_previous() method

### ISSUE THREAD

**Issue by dvkovner** [iambrandontaylor/django-admin-sortable#108]
Hello! Method get_previous() in Sortable class always return first value of queryset. I think that is related with this part of  _filter_objects() method in Sortable class:

        try:
            obj = self.__class__.objects.filter(**filters)[:1][0]
        except IndexError:
            obj = None

P.S. Sorry for my English :)

**Comment by alsoicode** [comment]
Hello. `.filter()` returns a queryset, so `[:1][0]` just limits the queryset to one item and returns it. The `**filters` key value arguments are passed in [here](https://github.com/iambrandontaylor/django-admin-sortable/blob/master/adminsortable/models.py#L89) for `get_next()` and [here](https://github.com/iambrandontaylor/django-admin-sortable/blob/master/adminsortable/models.py#L93) for `get_previous()`

**Comment by dvkovner** [comment]
I have two models inherited from Sortable class: Page and Record. Page model contains ForeignKey to Record. If i call get_previous() method of any of Record objects without any parameters, then i always get first record object (not previous). Is it normal?

class Record(Sortable):
    """
    Запись в книге почетных гостей
    """
    class Meta(Sortable.Meta):
        verbose_name = u'Запись'
        verbose_name_plural = u'Записи'

    author = models.CharField(verbose_name=u'Автор', max_length=255, unique=False, blank=False,
                              default=author_default)

class Page(Sortable):
    """
    Страница книги почетных гостей
    """

    class Meta(Sortable.Meta):
        verbose_name = u'Страница'
        verbose_name_plural = u'Страницы'

    record = SortableForeignKey(Record, verbose_name=u'Запись', related_name='pages', null=True, blank=True, default=None)
    image = models.ImageField(verbose_name=u'Картинка',
                              upload_to='pages',
                              default='',
                              help_text=u'Размер файла - до 10 MB. Формат PNG.',
                              validators=[ImageValidator(formats=['PNG'], max_size=10000000)])
    updated = models.DateTimeField(verbose_name=u'Обновление', auto_now=True, null=True,
                                   help_text=u'Время последнего изменения страницы на сервере')

**Comment by alsoicode** [comment]
That certainly doesn't sound correct. Can you show me how you're calling `.get_previous()`? I've refactored the [unit tests](https://github.com/iambrandontaylor/django-admin-sortable/blob/master/sample_project/app/tests.py#L170) for get next/previous to be more robust and they are passing for me.

**Comment by dvkovner** [comment]
```python
    def change_view(self, request, object_id, form_url='', extra_context=None):
        extra_context = extra_context or {}
        extra_context['prev_record'] = Record.objects.get(id=object_id).get_previous()
        extra_context['next_record'] = Record.objects.get(id=object_id).get_next()
        return super(RecordAdmin, self).change_view(request, object_id, form_url, extra_context=extra_context)
```

get_next() is working properly. get_previous() always return first record.

**Comment by alsoicode** [comment]
Can you give me a sample of the data? Keep in mind that if you have a SortableForeignKey field, the next/previous record will be returned relative to the SortableForeignKey. See: https://github.com/iambrandontaylor/django-admin-sortable#model-instance-methods for an explanation of which records will be returned for a sample data set.

**Comment by dvkovner** [comment]
I have sent the database to that address: alsoicode@gmail.com.

**Comment by alsoicode** [comment]
I created a new project using Django 1.8 and SQLite3. I removed the Cryllic portions of the code for simplicity and set up an app called "books" with the following models:

    from django.db import models
    from adminsortable.models import Sortable, SortableForeignKey


    class Record(Sortable):

        class Meta(Sortable.Meta):
            pass

        author = models.CharField(max_length=255, default='Someone')

        def __unicode__(self):
            return self.author


    class Page(Sortable):

        class Meta(Sortable.Meta):
            pass

        record = SortableForeignKey(Record, related_name='pages', null=True, blank=True, default=None)
        updated = models.DateTimeField(auto_now=True, null=True)

        def __unicode__(self):
            return '{} ID: {}'.format(self.record.__unicode__(), self.pk)

I created three "Record" instances via Django admin. When I drop into a Django shell, here's what I'm getting:

    Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
    [GCC 4.9.1] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    (InteractiveConsole)
    >>> from books.models import Record
    >>> records = Record.objects.all()
    >>> for record in records:
    ...      print record.get_previous(), record.get_next()
    ... 
    None Second Author
    First Author Third Author
    First Author None

The first record has no previous instance, so `None` is returned. The last instance has no next instance so `None` is returned. I'm not sure what's causing your code not to work, but as far as I can test, `get_previous()` is working as expected.

**Comment by alsoicode** [comment]
I stand corrected. The bug was staring me right in my output! I have pushed version 1.8.4 to PyPi which includes a fix for `get_previous`. Thanks for reporting this problem.

**Comment by dvkovner** [comment]
Hello! Sorry, I was busy working on the project and could not answer quickly. Indeed, the bug was obvious. :) Glad I could help you.

**Comment by alsoicode** [comment]
No worries. Sorry it took me so long to get that fixed! What a stupid
problem to have in the code in the first place; I must be getting old.

Best,
Brandon
