### ISSUE TITLE
show_change_link attribute has no effect on sortable inlines

### ISSUE THREAD

**Issue by jorge-marques** [iambrandontaylor/django-admin-sortable#109]
Django 1.8 added a show_change_link option to inlines, but django-admin-sortable does not seem to take this into account.

**Comment by jrief** [comment]
Is this a show blocker for Django-1.8.
Due to external constraints I'm still working with 1.7, so I'm not aware of these news.
Do you want to send a PR?

**Comment by jorge-marques** [comment]
The option adds a link to the change view of the object.
Here’s the relevant documentation, for reference:
https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.InlineModelAdmin.show_change_link <https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.InlineModelAdmin.show_change_link>

Yes, I can give it a try.

**Comment by alsoicode** [comment]
I'm currently slammed on other work. If you would be so kind as to provide a PR, I can review it asap.

**Comment by jorge-marques** [comment]
It's now working, although I haven't updated the sample application to demonstrate this capability. Not sure if it's worth it.

**Comment by alsoicode** [comment]
The sample app imports the working copy of adminsortable in the repo, so you don't have to update it. It should draw in the changes automatically.

**Comment by jorge-marques** [comment]
I meant adding an example with the show_change_link option enabled. Anyway, hope you can merge this when you have some time :)

**Comment by alsoicode** [comment]
Ah. All that would be required is to create a virtualenv with Django 1.8 installed and then run the sample app.
