### ISSUE TITLE
SortableStackedInline with collapse class in fieldsets adds empty divs when drop

### ISSUE THREAD

**Issue by cho-is** [iambrandontaylor/django-admin-sortable#114]
![screen shot 2015-11-18 at 11 13 58](https://cloud.githubusercontent.com/assets/4965837/11239683/608d7876-8de5-11e5-8d8c-2c1ae3ecae6b.png)

```
class ProjectBlockInline(SortableStackedInline):
    model = models.ProjectBlock
    extra = 0
    form = ProjectBlockInlineForm
    fieldsets = (
        ('Information', {
            'classes': ('collapse',),
            'fields': ('title', 'text', 'image', 'cover_image', 'cropping')
        }),
        ('Settings', {
            'classes': ('collapse',),
            'fields': ('show_title', 'layout', 'published', 'tags')
        }),
    )
```

**Comment by cho-is** [comment]
It needs to check if `collapse` class is there so then it does not add `display: block;` on `form-row` classes

I will try and see if I can find a solution for it

**Comment by cho-is** [comment]
Solved this by changing the following line in [admin.sortable.stacked.inlines.js](https://github.com/iambrandontaylor/django-admin-sortable/blob/master/adminsortable/static/adminsortable/js/admin.sortable.stacked.inlines.js#L43) 

to 
```
ui.item.find('h3').effect('highlight', {}, 1000);
```

**Comment by alsoicode** [comment]
Cool. Open a pull request please.

**Comment by cho-is** [comment]
Please notice this will just highlight the h3 title which I think is enough for a visual feedback

**Comment by alsoicode** [comment]
After some investigation, I've come up with an alternative fix:

    ui.item.find('.form-row').effect('highlight', {}, 1000).removeAttr('style');

which I'll get into the next release.

**Comment by alsoicode** [comment]
Ok, version 2.0.6 has been released to PyPi. Thanks for reporting this!

**Comment by cho-is** [comment]
Your solution does not highlight the element I am afraid

**Comment by alsoicode** [comment]
I tested it using the sample project in the source. Are you having issues
in a particular browser?

**Comment by cho-is** [comment]
Not highlighting on Chrome and Firefox.
Using django-flat-theme

**Comment by alsoicode** [comment]
If there's css or js that's overriding my css from django-flat-theme, then I'll have to investigate that as a separate issue.

**Comment by alsoicode** [comment]
Sorry, I didn't notice that all of the fieldsets were set to collapsed. This seems counterproductive, but, it's not impossible to allow for when selecting which element to highlight.

**Comment by alsoicode** [comment]
Ok, I put in some extra code to select which element to highlight in the case where all fieldsets are collapsed. In that case, it will highlight the `h3` as you had suggested, otherwise it highlights the `.form-row` as before.

I've tested this using the `ComponentInline` model in the sample project. I left the fieldsets in there, but commented out if you'd like to try it out.

**Comment by cho-is** [comment]
Nice! thank you sir!
