### ISSUE TITLE
Better discoverability for 'draggable'

### ISSUE THREAD

**Issue by andybak** [iambrandontaylor/django-admin-sortable#117]
I've switched to your project from a homebrew solution and it's better in nearly every way. However - there's one thing I miss.

I added 'gripper' drag handles to the right-hand edge of each admin inline row to make it more obvious that you can drag a row to reorder it.

This isn't the perfect solution but I think something visible is needed as a hint to users that it's possible to drag. Simply changing the cursor is a touch too easy to miss in my view.

**Comment by alsoicode** [comment]
Thank you. Can you share a screenshot?

**Comment by andybak** [comment]
Yep. Although as I mentioned I think it needs improving.

And here's the code:
 https://github.com/DjangoAdminHackers/django-admin-sortable/blob/master/admin_sortable/static/js/admin_sortable/admin_sortable.js

![screenshot-www thelilyfoundation org uk 2015-12-05 15-11-26](https://cloud.githubusercontent.com/assets/60035/11608480/8417eb0c-9b62-11e5-8296-f0d39921739a.png)

**Comment by alsoicode** [comment]
Just wanted to drop you a line to let you know I haven't forgotten about you :)

I'm currently working on adding a font icon based solution for this.

**Comment by andybak** [comment]
Thanks!

**Comment by alsoicode** [comment]
@andybak I just released 2.0.9 which has sortable icons from Font Awesome. Give it a whirl!
