### ISSUE TITLE
UX improvements to 'unsaved changes'

### ISSUE THREAD

**Issue by andybak** [iambrandontaylor/django-admin-sortable#118]
Currently a system modal dialog is used to tell users to save changes before saving.

In my previous home-brewed solution to this, I instead updated a hidden order field so that the new ordering was only saved when the modal itself was saved. In some ways I prefer your approach but I does create introduce a new problem that you've used this modal to solve.

Modals are a bit unpleasant in terms of UX - both visually and the fact you have to click to dismiss them. I've got a few thoughts:

1. Something less obstructive - a brief position:fixed flash message that fades out?
2. Is there a way to avoid this entirely? Could the new ordering be written to the db in such a way that it doesn't matter that there are unsaved changes? I'm guessing behind the scenes you're not doing queryset.update probably to avoid bypassing instance.save() However - would it be safe to update a single field and thus relax the restriction on unsaved changes?

**Comment by alsoicode** [comment]
I'm actually not overriding the built-in Django messaging about unsaved changes at all. On every drag and drop, regardless of the state of the parent element, since I'm assuming we're talking about inlines here, an array of key/value pairs is sent via ajax and the ordering is updated.

**Comment by alsoicode** [comment]
Closing this for now, as it would necessitate changes to Django itself.
