### ISSUE TITLE
jQuery library loading on Django 1.9

### ISSUE THREAD

**Issue by KuroiDOC** [iambrandontaylor/django-admin-sortable#120]
When tried to use the project on Django 1.9 I was unable to sort my objects (nothing happened when dragged) because it fails to load jQuery on template change_list.html:12 from static root at admin/js/jquery.js (it seems on Django 1.9 it has been moved to admin/js/vendor/jquery/ directory https://docs.djangoproject.com/en/1.9/releases/1.9/)

I have modified it by hand and now I can freely sort my objects

**Comment by alsoicode** [comment]
Ah. I haven't had a chance to take a look at 1.9 yet. I'll try to get a patch in this week, or if you'd like, make a PR and I'll take a look.

**Comment by camilonova** [comment]
@alsoicode There is a patch in #121 can you release a new version including this fix?

Thanks.

**Comment by alsoicode** [comment]
Ok, https://github.com/iambrandontaylor/django-admin-sortable/pull/121 has been merged.

**Comment by camilonova** [comment]
Thanks pal, can we have a release too?

**Comment by alsoicode** [comment]
Yes. I'm working on it. I'm seeing another issue though with generic content types on 1.9, so I need to take a look at that.

**Comment by alsoicode** [comment]
Ugh. Looks like the generics have been refactored quite a bit for 1.9. I don't have time to look into this right now, but I'll do my best to look at it today.

**Comment by alsoicode** [comment]
So, luckily this turned out to be just a simple matter of an import refactor on the sample project. It doesn't affect the adminsortable core functionality at all.

**Comment by alsoicode** [comment]
@camilonova 2.0.8 has been released to PyPi

**Comment by camilonova** [comment]
@alsoicode thank you! :santa:

**Comment by alsoicode** [comment]
You're welcome. I've run the tests and done some manual testing too, but please let me know if you run into any issues.
