### ISSUE TITLE
Sources missing for jQuery UI

### ISSUE THREAD

**Issue by JaapJoris** [iambrandontaylor/django-admin-sortable#129]
The file `jquery-ui-django-admin.min.js` in directory [adminsortable/static/adminsortable/js/](https://github.com/iambrandontaylor/django-admin-sortable/tree/master/adminsortable/static/adminsortable/js) is a minified version of a (possibly customized?) jQuery UI library. It would be very nice if the original source for this file was also made available.

**Comment by alsoicode** [comment]
Apologies, but unfortunately I don't have this file anymore. From what I can remember, the change I made to it was mostly around namespacing. Since Django admin provides its own jQuery, I had referenced jQuery using django.jQuery instead of window.jQuery.
