### ISSUE TITLE
CSRF cookie name

### ISSUE THREAD

**Issue by BUHARDI** [iambrandontaylor/django-admin-sortable#130]
I'm getting an 403 error when sorted items are sent to server by AJAX POST request. This problem occurs if i have changed default value of [CSRF_COOKIE_NAME](https://docs.djangoproject.com/en/1.9/ref/settings/#csrf-cookie-name) setting. Blame on [jquery.django-csrf.js](https://github.com/iambrandontaylor/django-admin-sortable/blob/master/adminsortable/static/adminsortable/js/jquery.django-csrf.js) :(

I think this should be overwritten using in HTML dynamically injected CSRF token. In this case you wouldn't need [jquery.django-csrf.js](https://github.com/iambrandontaylor/django-admin-sortable/blob/master/adminsortable/static/adminsortable/js/jquery.django-csrf.js) anymore :)

**Comment by alsoicode** [comment]
I can just pick up the name from settings and set that in a client-side variable for jquery.django-csrf.js to pick up, somewhere before here: https://github.com/iambrandontaylor/django-admin-sortable/blob/master/adminsortable/templates/adminsortable/change_list.html#L16 and here: https://github.com/iambrandontaylor/django-admin-sortable/blob/master/adminsortable/templates/adminsortable/change_form.html#L11

**Comment by alsoicode** [comment]
Ok, I have released 2.0.11 to PyPi that fixes this issue for you.
