### ISSUE TITLE
Sorting succeeds on StackedInlines, but fails on TabularInlines

### ISSUE THREAD

**Issue by JaapJoris** [iambrandontaylor/django-admin-sortable#134]
Hi there,

I have encountered the following bug with adminsortable version 2.0.12 and Django 1.9.2. When using a SortableTabularInline admin, the form rows can be dragged and dropped but the Ajax POST requests always returns the following response:

    {objects_sorted: false}

Hence, when reloading the page the objects are again in their original order. For debugging purposes I have changed [line 307 of admin.py](https://github.com/iambrandontaylor/django-admin-sortable/blob/master/adminsortable/admin.py#L307) from `pass` into `raise`, and then the POST request returns the following error:

    Exception Type: ValueError at /admin/autodidact/assignment/sorting/do-sorting/16/
    Exception Value: invalid literal for int() with base 10: ''
    Request information:
    GET: No GET data
    POST:
    indexes = u''

It seems that the variable `indexes` is empty, and that's why the sorting fails. I tried stepping through the Javascript code but I couldn't find a reason why `indexes` could be empty. This problem only occurs with SortableStackedInline. If I change my own `admin.py` to SortableStackedInline the sorting succeeds every time.

**Comment by alsoicode** [comment]
Interesting. I'm not sure why that would fail, but I will look into it asap.

**Comment by JaapJoris** [comment]
It's a hard bug to reproduce. If it helps, I have created a [minimal working example here](https://github.com/JaapJoris/autodidact/tree/adminsortable-mwe). It's an orphan branch of a much bigger code base that also exhibits the problem.

**Comment by alsoicode** [comment]
Haven't had a chance to take a look yet. My "to do" list looks like the dead sea scrolls at the moment.

**Comment by alsoicode** [comment]
First, sorry for the huge delay getting back to you. I was super busy then got sick. Ugh.

I have a virtualenv for this project, and I updated it to Django 1.9.2, and modified the `sample_project` to match the new `@admin.register()` decorator as well. In the first screenshot is the sample app's admin.py:

![admin py -home-btaylor-django-projects-django-admin-sortable atom_008](https://cloud.githubusercontent.com/assets/86738/13554435/caabad6e-e375-11e5-88aa-3d5277325dbf.jpg)

The `CreditInline` class inherits from `SortableTabularInline` and is in the `ProjectAdmin` inlines. When I perform sorting on the Credits:

![change project django site admin - google chrome_007](https://cloud.githubusercontent.com/assets/86738/13554448/ff1dd810-e375-11e5-8af2-9106017932c8.jpg)

I'm getting a successful sort. Are you perhaps doing an override of one of the templates that adminsortable uses?

**Comment by alsoicode** [comment]
@JaapJoris Can you please upgrade to 2.0.13? I'd like to see if maybe you were experiencing this issue: https://github.com/iambrandontaylor/django-admin-sortable/pull/136 which is fixed in that release.

**Comment by JaapJoris** [comment]
@alsoicode sorry for not getting back to you sooner. I cannot reproduce this bug anymore, neither with version 2.0.12 nor 2.0.13. So it's been a good call to close this issue :-) Sorry for bothering you.

**Comment by alsoicode** [comment]
No worries at all, and bug me anytime! I'm always looking for ways to make this plugin better. I was hoping by now the Django core team would have pulled my code into Django proper, but, alas, they have not. Sigh.
