### ISSUE TITLE
can't find jquery.django-csrf.js

### ISSUE THREAD

**Issue by avoine** [iambrandontaylor/django-admin-sortable#135]
Is it possible that you forget to add it?

**Comment by alsoicode** [comment]
Nope. That file has been moved to an include to support using a custom csrf cookie name. The includes are at:

https://github.com/iambrandontaylor/django-admin-sortable/blob/master/adminsortable/templates/adminsortable/change_form.html#L11

and 

https://github.com/iambrandontaylor/django-admin-sortable/blob/master/adminsortable/templates/adminsortable/change_list.html#L16
