### ISSUE TITLE
problem using custom name for order field

### ISSUE THREAD

**Issue by willhardy** [iambrandontaylor/django-admin-sortable#137]
It appears as though a stray "finally" means that any custom name for the order field is overwritten with `'order'` no matter what, [see the code here] (https://github.com/iambrandontaylor/django-admin-sortable/blob/ada42c84deeb283613cd78346bff45dd2da6915f/adminsortable/admin.py#L192-L198)

(I'm not even sure if the code needs to specify the default value, as it should theoretically always be available in `Meta.ordering`)

**Comment by alsoicode** [comment]
That's to support legacy implementations of Sortable models, where the `order` field was hardcoded. I haven't experienced a problem with this. Can I see your model?

**Comment by willhardy** [comment]
But no matter which line matches in the try/except, the variable will be then overridden with `'order'` upon exiting the block. After these lines, the variable cannot have a value other than `'order'`, ie replacing the entire block with just `order_field_name = 'order'` would be functionally equivalent.

**Comment by willhardy** [comment]
This is what I mean, below the name `a` will never leave the block with a value other than `3`:

    >>> try:
    ...   a = 1
    ... except ValueError:
    ...   a = 2
    ... finally:
    ...   a = 3
    ...
    >>> print(a)
    3
    >>> try:
    ...   a = 1
    ...   raise ValueError()
    ... except ValueError:
    ...   a = 2
    ... finally:
    ...   a = 3
    ...
    >>> print(a)
    3

**Comment by alsoicode** [comment]
Yes, you're correct. I forgot that `finally` is executed regardless of
whether or not an exception actually occurs. I'm refactoring this as I type.

**Comment by alsoicode** [comment]
OK, I have released version 2.0.14 on PyPi which fixes this.

**Comment by alsoicode** [comment]
Sorry, please don't update yet. Had a problem with the release.

**Comment by alsoicode** [comment]
Ok, sorry about that. Please update to 2.0.15

**Comment by willhardy** [comment]
Thanks for the quick fix!

**Comment by alsoicode** [comment]
You're welcome. Sorry for the careless mistake.
