### ISSUE TITLE
Sort icons next to each field (stacked inline / Django 1.9)

### ISSUE THREAD

**Issue by jaap3** [iambrandontaylor/django-admin-sortable#138]
I'm assuming it's not supposed to draw the sort icons next to each field of a stacked inline.

![screen shot 2016-05-18 at 15 23 06](https://cloud.githubusercontent.com/assets/48517/15360082/7c795008-1d0c-11e6-91a8-1a54cae71df9.png)

**Comment by jaap3** [comment]
Seems like `forloop.first` does not work. It's always `True` for each iteration of the `for field in line` loop in `adminsortable/shared/fieldset.html`.

**Comment by alsoicode** [comment]
Hmm. That *is* odd. The icons are supposed to be there, but ones in the middle should be showing an up and down caret. I'll try to take a look later today.

**Comment by jaap3** [comment]
Sorry for the crummy screenshot. The issue is that the arrows are shown for every field in every inline, instead of only for the first field of every inline.

**Comment by alsoicode** [comment]
ah. now that is definitely not supposed to happen

**Comment by jaap3** [comment]
Did you get around to looking at this issue? Is there anything I can do to help you out?

**Comment by alsoicode** [comment]
I'm slammed between 3 different projects at the moment. If you'd like to take a look at this issue, it would be much appreciated.

**Comment by alsoicode** [comment]
@jaap3 Can you please update to 2.0.16 and see if this is still an issue for you?

**Comment by jaap3** [comment]
It's still an issue. I've created an example project to reproduce it: https://github.com/jaap3/adminsortable-issue-138

**Comment by vstoykov** [comment]
I used the project provided by @jaap3 and tried different django and django-admin-sortable versions and found that the regression was happened in django-admin-sortable 2.0.9. In 2.0.8 it works correctly.

**Comment by vstoykov** [comment]
Actually now I see that the main difference between 2.0.8 and 2.0.9 is that in 2.0.9 these icons are introduced and it seems that this is an issue from beginning and not a regression.

**Comment by jaap3** [comment]
OK so it's intended behaviour? Sure looks strange though.

**Comment by vstoykov** [comment]
I don't think that it is intended behavior. Probably because these icons are for sorting objects list mainly and probably are not tested with inlines or something.

**Comment by alsoicode** [comment]
Hi guys. Sorry I haven't had a chance to look into this yet. I'll try to do so today; I've just been extremely short on time of late due to ongoing projects.

**Comment by jaap3** [comment]
No worries. Have you considered moving this project to [Jazzband](https://jazzband.co/)?

**Comment by vstoykov** [comment]
@jaap3 Can you try the code from my PR (#147) to see if it is working now?
