### ISSUE TITLE
Ordering a large list of items

### ISSUE THREAD

**Issue by ncharlot** [iambrandontaylor/django-admin-sortable#139]
Hi,

I'm looking for a solution to ease ordering of items in a large list (hundreds of items).
Drag & drop as became complicated to use. It would be easier to set directly the order wanted but I guess it's a common issue. So any idea?

Thanks

**Comment by alsoicode** [comment]
Good question. Drag and Drop ordering does get problematic with long lists. Are you needing quick ways to move items to specific positions like first or last? or to a specific interval like 10th or 20th, etc?

**Comment by alsoicode** [comment]
Closing for now.
