### ISSUE TITLE
Wrong AJAX url for admin sorting

### ISSUE THREAD

**Issue by vstoykov** [iambrandontaylor/django-admin-sortable#142]
Currently for every registered model there is attached url with model_id parameter. All of these URLs will be with the same name and when resolved in template will point to last registered. For example if I have `app1` with models `App1Model1` and `App1Model2` and `app2` with models `App2Model1` and `App2Model2` and all of them are `Sortable` and registered in admin I will have these URLs:

    /admin/app1/model1/sorting/do-sorting/<model_id>/
    /admin/app1/model2/sorting/do-sorting/<model_id>/
    /admin/app2/model1/sorting/do-sorting/<model_id>/
    /admin/app2/model2/sorting/do-sorting/<model_id>/

Now I can order all models on all urls. For example if `App1Model2` is with `model_id==2` then  I can order the items in any of this URLs:

    /admin/app1/model1/sorting/do-sorting/2/
    /admin/app1/model2/sorting/do-sorting/2/
    /admin/app2/model1/sorting/do-sorting/2/
    /admin/app2/model2/sorting/do-sorting/2/

The same goes for any other model. In fact all models will be sorted in the URL registered last. For example if I register `App2Model2` last then all models will be sorted at the urls under:

    /admin/app2/model2/sorting/do-sorting/<model_id>

This all goes with AJAX and is unnoticed for users but is somehow counter intuitive.
Also there is no permission check which which will restrict access for sorting to people which does not have change permissions to given model.

The correct way of doing this will be to do the sorting for every model in the respective URLs. For example:

    /admin/app1/model1/sorting/do-sorting/
    /admin/app1/model2/sorting/do-sorting/
    /admin/app2/model1/sorting/do-sorting/
    /admin/app2/model2/sorting/do-sorting/

I will try to prepare PR for that.

One question though - Which is the minimum Django version that is supported?

**Comment by vstoykov** [comment]
Now I saw that this URL is used to do the sorting for inline models.

I created the PR and preserved the logic for doing inline sorting in URL which has model ID in it but restricted it only for IDs of the registered inline models.

You can see my PR which is not fully ready yet. I need to make tests for permission checking but I wanted to show may changes early if you have any thoughts, concerns or whatever.

**Comment by vstoykov** [comment]
I updated my PR with tests. You can look at it and if you don't have any objections I'll be glad if you merge it.

Thanks.

**Comment by raaveer** [comment]
Hi,

I have similar problem in Django 1.7.7, i'm using SortableTabularInline like this:

`class SomeChildInline(SortableTabularInline):`
`model = SomeChildModel`

`class SomeParentModelAdmin(SortableAdminModel):`
`model = SomeParentModel`
`inlines = [ SomeInline, ]`

An when I'm trying to sort SomeChildModel items in SomeParentModelAdmin view, the sort request url directs to parent instead module action

**Comment by alsoicode** [comment]
I'll try to take a closer look at this problem this evening.
