### ISSUE TITLE
Consider dropping support for Django < 1.8

### ISSUE THREAD

**Issue by jaap3** [iambrandontaylor/django-admin-sortable#144]
With Django 1.10 on it's way and Django 1.8 (as an LTS) being the lowest version still receiving security fixes it seems reasonable to drop support for Django < 1.8. 

This also means removing all workarounds and version checks that are in the code.

**Comment by orzel** [comment]
I'd support this, indeed.

**Comment by alsoicode** [comment]
I agree this is probably a good idea. I'm just always so short on time. I'd welcome a pull request if someone would like to take this on.

**Comment by camilonova** [comment]
@alsoicode I could work and set up a team to work on improve this library.

Brandon would you agree to move this project to https://github.com/jazzband so we can add more people in here?

**Comment by alsoicode** [comment]
@camilonova I always welcome pull requests, but I'm not interested in moving the repo for the time being.

**Comment by alsoicode** [comment]
@camilonova version 2.0.22 has been released to PyPi.

**Comment by alsoicode** [comment]
Closing with https://github.com/iambrandontaylor/django-admin-sortable/pull/168
