### ISSUE TITLE
Support for older Django versions

### ISSUE THREAD

**Issue by 153957** [iambrandontaylor/django-admin-sortable#152]
The readme states:

> For Django 1.5.x to 1.9.x, use version 2.0.18 or below.

However, as far as I can see only Django 1.5 support was dropped (no longer tested), and 1.7.7 on Py3.5. The tests still pass for most combinations of Django and Python.

Shouldn't Django 1.8+ still be supported for the foreseeable future? (Related to #144)

**Comment by alsoicode** [comment]
Yes, Django 1.8 or higher is still supported.
