### ISSUE TITLE
It is possible to drag the table header

### ISSUE THREAD

**Issue by utapyngo** [iambrandontaylor/django-admin-sortable#154]
Django 1.9.9
django-admin-sortable 2.0.18

![image](https://cloud.githubusercontent.com/assets/1124655/19594119/e8a38bb0-97ad-11e6-8540-d758fdcc634a.png)

**Comment by alsoicode** [comment]
Are you saying that you're able to drag the blue bar with the text "Choices - Drag and drop to change order" If so, I'm not seeing the same behavior.

**Comment by alsoicode** [comment]
Closing as I can't reproduce the issue. Will re-open if necessary.
