### ISSUE TITLE
Drag and drop of a a parent object doesn't save

### ISSUE THREAD

**Issue by Ivan34** [iambrandontaylor/django-admin-sortable#156]
Hi,
For my application, I implemented exactly the first common use case of your documentation.
I have sortable Projects which have sortable categories as foreign key. When I try to reorder Categories, it works correctly. When I try to reorder Projects inside a category, it works. But on this last view, if I try to reorder Categories it will not be saved. I tried with the sample_project and there is the bug if you go to: http://127.0.0.1:8000/admin/app/project/sort/ and try to reorder categories. If you refresh your page, they will come back at their initial position.
I think it is a bug but maybe I just have to add something in my code to fix this...

**Comment by alsoicode** [comment]
Well I'll be damned, and I'll figure out what's going on with this.

**Comment by alsoicode** [comment]
Well, the good news is that the data is saving correctly. If I run the sample project and re-order categories for a project, the data is correct upon inspection of the database. Something is causing the objects to be displayed in the wrong order when returning to the list view. Still investigating.

**Comment by alsoicode** [comment]
Seems that the sortable foreign key isn't being saved correctly.

**Comment by alsoicode** [comment]
This pull request: https://github.com/iambrandontaylor/django-admin-sortable/pull/143 completely messed up the admin URL structure for sorting foreign keys. I'm in the process of fixing it.

**Comment by alsoicode** [comment]
Please upgrade to 2.0.21 which fixes the regression. My apologies for the inconvenience.

**Comment by Ivan34** [comment]
Perfect, Thank you!

**Comment by alsoicode** [comment]
You're welcome
