### ISSUE TITLE
No 2.0.18 in tags

### ISSUE THREAD

**Issue by jowan** [iambrandontaylor/django-admin-sortable#159]
Hi there,

I don't see 2.0.18 in the list of tags.
This is the one suggested for Django 1.5.x to 1.9.x ?

PIP does work though with specifying it.

**Comment by alsoicode** [comment]
Gah. That's my fault. I'll get the missing tags for those versions in this
evening.

**Comment by jowan** [comment]
Thanks - just thought it was relevant as you were referencing it
specifically.

**Comment by alsoicode** [comment]
Fixed.
