### ISSUE TITLE
Django 1.5 AttributeError: 'Options' object has no attribute 'model_name'

### ISSUE THREAD

**Issue by uraz** [iambrandontaylor/django-admin-sortable#161]
In admin.py, line: 109 should be. `opts.module_name`

**Comment by alsoicode** [comment]
For Django 1.5, you need to use version 2.0.18 or earlier.

**Comment by uraz** [comment]
Good to know. Thanks.

**Comment by alsoicode** [comment]
Closing. If you're still having trouble, I'll re-open.
