### ISSUE TITLE
How to proceed with an existing order field

### ISSUE THREAD

**Issue by rhymes** [iambrandontaylor/django-admin-sortable#85]
Hello, I have a bunch of models using a custom "order" field and I'd like to start using django-admin-sortable, what's the best approach? The README deals with existing models with no order field, but what about existing models with an existing order field?

My field is simply: order = models.IntegerField(default=0) and it's valued by the user in the admin.

Any ideas? Shall I rename this field, inherit from Sortable and copy the existing values over with a migration or is there a better approach?

**Comment by jrief** [comment]
I had the same problem and therefore rewrote this module taking a different approach.
You can find it here:
https://github.com/jrief/django-admin-sortable2
